print(f"##############################")
print(f"#                            #")
print(f"#      Muhammad Naufal       #")
print(f"#       2610817210008        #")
print(f"#                            #")
print(f"##############################")